### ISSUE TITLE
Weight matrix dimensions after transofrmation

### ISSUE THREAD

**Issue by SrinjaySarkar** [pbloem/former#17]
This might be a dumb question.
Could you explain the dimensions of the weight matrix after transforming the input with K,Q,V?
![Screenshot 2020-12-21 161852](https://user-images.githubusercontent.com/25768975/102769728-12455600-43a9-11eb-9606-e8073f0a70a5.png)

I tried doing it myself , am I overlooking an obvious error here?
Assuming a batch size of 1 for simplicity.
![22573](https://user-images.githubusercontent.com/25768975/102769842-35700580-43a9-11eb-9ae4-768c2a77fe3a.jpg)

**Comment by pbloem** [comment]
The weight matrix (w_{ij}) is always l by l where l is the length of the input sequence. The video that is now linked at the top of the blog post has some additional diagrams that might be helpful for understanding the vectorized implentation of self attention.

Note that it doesn't matter whether you apply the KQV transforms or not; these only change the embedding dimension, and that is mulitplied out because you're computing the dot product of every key with every query.

If you have multiple heads, you get one l by l matrix for every head.
