### ISSUE TITLE
Why the use of log_softmax ?

### ISSUE THREAD

**Issue by dsantiago** [pbloem/former#36]
Trying to understand why you used `log_softmax`instead of `softmax` as it will not reproduce a probability distribution that sums to 1 in the end? I'm missing something?

**Comment by pbloem** [comment]
Yes, it will. You just get the logarithms of the probabilities. if you take their exp(), they will sum to one.

By always talking about log probabilities instead of probabilities, we get better numerical stability, especially when dealing with small probabilities. 

See also: https://mlvu.github.io/preliminaries/#slide-014
