### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'triu_indices'

### ISSUE THREAD

**Issue by xxxyy95** [pbloem/former#7]
When I run the code and set the mask to True, the following problem occurs:

AttributeError: module 'torch' has no attribute 'triu_indices'

def mask_(matrices, maskval=0.0, mask_diagonal=True):
    b, h, w = matrices.size()
    indices = **torch.triu_indices**(h, w, offset=0 if mask_diagonal else 1)
    matrices[:, indices[0], indices[1]] = maskval

**Comment by pbloem** [comment]
Could it be that you're running an older version of pytorch? triu_indices is a relatively recent addition.

If you installed with pip, you can upgrade with ```pip install torch --upgrade```

**Comment by xxxyy95** [comment]
Thank you for your reply. What's your version of pytorch?Does triu_indices need the latest version?
In addition, I have another question that I would like to ask, 
`self.ff = nn.Sequential(

            nn.Linear(emb, ff_hidden_mult * emb),

            nn.ReLU(),

            nn.Linear(ff_hidden_mult * emb, emb)

        )`
`fedforward = self.ff(x)`
what is the specific function or meaning of self.ff here?
Looking forward to your reply,thank you.

**Comment by pbloem** [comment]
It works for me on pytorch 1.2.0 The function was first included in 1.1.0, I think.

```self.ff``` is the feedforward layer that is applied to every vector independently (in between the self attention layers). These are represented as green "MLP" rectangles in the illustration of the transformer block.

**Comment by xxxyy95** [comment]
Thank you for your reply. 
I want to figure out what role does MLP play in this model?That is, why add the feedforward layer here?Because I find that the size of tensor hasn't changed after the feedforward layer,so i am eager to know what is the effect of doing some linear and nonlinear operations (the operation of feedforward layer)?Is it redundant? Can we delete it?

**Comment by pbloem** [comment]
I tried to find some background or analysis on this, but I don't think the question has been answered properly.

Here's my best guess (just a hypothesis though, there's no guarantee that this is true).

The self attention is a powerful non-linear operation, but it does not _expand _ the representation. Having a hidden layer that is wider than the input layer is necessary for a neural network to be able to compute certain functions.

We could add this behavior to the self-attention, for instance by computing the keys, queries and values with a two-layer network (instead of the linear transformation we use now). That would probably allow us to get rid of the feedforwards, and use only self attention layers. 

However, this would make the network more expensive. The standard architecture does two things 1) let words in the input interact and 2) apply nonlinear transformations. We make the first a linear global operation, and the second a nonlinear local operation to make the computation more efficient.

There is
